include: package:leancode_lint/analysis_options.yaml

# Optional lint rules configuration
custom_lint:
  rules:
    - prefix_widgets_returning_slivers:
      application_prefix: StartingFlutterProject # TODO Change
    # This forces the use of some specific class instead of another.
    - use_design_system_item:
      # AppText:
      #   - instead_of: Text
      #     from_package: flutter
      #   - instead_of: RichText
      #     from_package: flutter
      # AppScaffold:
      #   - instead_of: Scaffold
      #     from_package: flutter

analyzer:
  errors: 
    # e.g. creating an empty Map or List would require specify the type of them
    inference_failure_on_collection_literal: ignore

  plugins:
    # Required for our custom lints support
    - custom_lint
  exclude:
    - '**/*.g.dart'


linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - cancel_subscriptions
    - close_sinks
    - prefer_const_literals_to_create_immutables
    - avoid_types_on_closure_parameters: false