name: starting_flutter_project
description: Template for starting Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  envied: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_config_plus: ^1.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  golden_toolkit: ^0.15.0
  intl: ^0.19.0
  meta: ^1.15.0

dev_dependencies:
  bloc_test: ^9.1.7
  custom_lint: ^0.7.0
  dart_code_linter: ^1.1.3
  envied_generator: ^1.0.0
  flutter_test:
    sdk: flutter
  golden_test:
    git: 
      url: https://github.com/dmkasperski/golden_test
      ref: add_support_for_router
  leancode_lint: ^14.3.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
