# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end

require 'dotenv'
Dotenv.load

platform :android do

  lane :upload_to_firebase do |options|
    # build_android_app action uses default entry point `lib/main.dart`.
    # Project uses different one depending on flavor.
    # So here we copy appropriate entry point to the default path.
    FileUtils.cp(ENV["MAIN_FILE_PATH"], "../../lib/main.dart")

    # Set default value if version_name is not provided. e.g.
    # fastlane android upload_to_firebase --env prod version_name:"version name" 
    version_name = options.fetch(:version_name, '1.0.0')

    build_android_app(
      task: "assemble",
      flavor: ENV["FLAVOR"],
      build_type: "Release",
      properties: { 
        'versionCode' => 1, 
        'versionName' => version_name,
      }
    )
    
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      service_credentials_file: ENV["FIREBASE_SERVICE_CREDENTIALS_FILE_PATH"],
      android_artifact_type: "APK",
      android_artifact_path: ENV["ANDROID_ARTIFACT_PATH"],
      groups: "testers",
    )
  end
end


